{
  "hash": "99e134796a79f7517c8711caaad07645",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Class 8: Breast Cancer Mini Project\"\nauthor: \"Matthew Huang (A17978767)\"\ndate: \"01/29/2026\"\nformat: pdf\n---\n\n## Background\n\nToday we will employ all R techniques for data analysis we used so far including machine learning methods of clustering and PCA to analyze an actual breast cancer biopsy data. \n\n## Data Import\n\nThe data is in CSV format:\n\n::: {.cell}\n\n```{.r .cell-code}\nwiscancer <- read.csv(\"WisconsinCancer.csv\", row.names=1)\n\nhead(wiscancer,3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n         diagnosis radius_mean texture_mean perimeter_mean area_mean\n842302           M       17.99        10.38          122.8      1001\n842517           M       20.57        17.77          132.9      1326\n84300903         M       19.69        21.25          130.0      1203\n         smoothness_mean compactness_mean concavity_mean concave.points_mean\n842302           0.11840          0.27760         0.3001             0.14710\n842517           0.08474          0.07864         0.0869             0.07017\n84300903         0.10960          0.15990         0.1974             0.12790\n         symmetry_mean fractal_dimension_mean radius_se texture_se perimeter_se\n842302          0.2419                0.07871    1.0950     0.9053        8.589\n842517          0.1812                0.05667    0.5435     0.7339        3.398\n84300903        0.2069                0.05999    0.7456     0.7869        4.585\n         area_se smoothness_se compactness_se concavity_se concave.points_se\n842302    153.40      0.006399        0.04904      0.05373           0.01587\n842517     74.08      0.005225        0.01308      0.01860           0.01340\n84300903   94.03      0.006150        0.04006      0.03832           0.02058\n         symmetry_se fractal_dimension_se radius_worst texture_worst\n842302       0.03003             0.006193        25.38         17.33\n842517       0.01389             0.003532        24.99         23.41\n84300903     0.02250             0.004571        23.57         25.53\n         perimeter_worst area_worst smoothness_worst compactness_worst\n842302             184.6       2019           0.1622            0.6656\n842517             158.8       1956           0.1238            0.1866\n84300903           152.5       1709           0.1444            0.4245\n         concavity_worst concave.points_worst symmetry_worst\n842302            0.7119               0.2654         0.4601\n842517            0.2416               0.1860         0.2750\n84300903          0.4504               0.2430         0.3613\n         fractal_dimension_worst\n842302                   0.11890\n842517                   0.08902\n84300903                 0.08758\n```\n\n\n:::\n:::\n\n> Q1 How many observations are in this dataset?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnrow(wiscancer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 569\n```\n\n\n:::\n:::\n\n\n> Q2 How many of the observations have a malignant diagnoss?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(wiscancer$diagnosis == \"M\")\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 212\n```\n\n\n:::\n\n```{.r .cell-code}\ntable(wiscancer$diagnosis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n  B   M \n357 212 \n```\n\n\n:::\n:::\n\n\n> Q3 How many variables/ features in the data are suffixed with _mean\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(wiscancer)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"diagnosis\"               \"radius_mean\"            \n [3] \"texture_mean\"            \"perimeter_mean\"         \n [5] \"area_mean\"               \"smoothness_mean\"        \n [7] \"compactness_mean\"        \"concavity_mean\"         \n [9] \"concave.points_mean\"     \"symmetry_mean\"          \n[11] \"fractal_dimension_mean\"  \"radius_se\"              \n[13] \"texture_se\"              \"perimeter_se\"           \n[15] \"area_se\"                 \"smoothness_se\"          \n[17] \"compactness_se\"          \"concavity_se\"           \n[19] \"concave.points_se\"       \"symmetry_se\"            \n[21] \"fractal_dimension_se\"    \"radius_worst\"           \n[23] \"texture_worst\"           \"perimeter_worst\"        \n[25] \"area_worst\"              \"smoothness_worst\"       \n[27] \"compactness_worst\"       \"concavity_worst\"        \n[29] \"concave.points_worst\"    \"symmetry_worst\"         \n[31] \"fractal_dimension_worst\"\n```\n\n\n:::\n\n```{.r .cell-code}\nlength(grep(\"_mean\",colnames(wiscancer)))\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 10\n```\n\n\n:::\n:::\n\n\nWe need to remove the `diagnosis` column before doing any more analysis of this dataset since we don't want to pass this to PCA etc. Save it as a separate vector that we can later use to compare findings to those of experts. \n\n\n::: {.cell}\n\n```{.r .cell-code}\n#saving diagnosis\ndiagnosis <- wiscancer [,1] \n#dataframe omitting first column\nwisc <- wiscancer[,-1]  \n```\n:::\n\n\n## Principal Component Analysis (PCA)\n\nThe primary function in base R for performing PCA is `prcomp()`. We use the optional argument `scale = TRUE` because the variables in the dataset are measured on different scales.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwisc.pr <- prcomp(wisc,scale=T)\n```\n:::\n\n\n> Q4. From your results, what proportion of the original variance is captured by the first principal component (PC1)?\n\n0.4427\n\n> Q5. How many principal components (PCs) are required to describe at least 70% of the original variance in the data?\n\n3\n\n> Q6. How many principal components (PCs) are required to describe at least 90% of the original variance in the data?\n\n7\n\n## Interpreting PCA Plots\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbiplot(wisc.pr)\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q7. What stands out to you about this plot? Is it easy or difficult to understand? Why?\n\nIt's not a good plot, since not much information is discernable. It is hard to understand due to there just being one large clump of data in the middle, making it too crowded with insufficient scaling to observe correlations visually. \n\n\n## Scatter plot observations by components 1 and 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\nggplot(wisc.pr$x) +\n  aes(PC1, PC2, col=diagnosis) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nsummary(wisc.pr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                          PC1    PC2     PC3     PC4     PC5     PC6     PC7\nStandard deviation     3.6444 2.3857 1.67867 1.40735 1.28403 1.09880 0.82172\nProportion of Variance 0.4427 0.1897 0.09393 0.06602 0.05496 0.04025 0.02251\nCumulative Proportion  0.4427 0.6324 0.72636 0.79239 0.84734 0.88759 0.91010\n                           PC8    PC9    PC10   PC11    PC12    PC13    PC14\nStandard deviation     0.69037 0.6457 0.59219 0.5421 0.51104 0.49128 0.39624\nProportion of Variance 0.01589 0.0139 0.01169 0.0098 0.00871 0.00805 0.00523\nCumulative Proportion  0.92598 0.9399 0.95157 0.9614 0.97007 0.97812 0.98335\n                          PC15    PC16    PC17    PC18    PC19    PC20   PC21\nStandard deviation     0.30681 0.28260 0.24372 0.22939 0.22244 0.17652 0.1731\nProportion of Variance 0.00314 0.00266 0.00198 0.00175 0.00165 0.00104 0.0010\nCumulative Proportion  0.98649 0.98915 0.99113 0.99288 0.99453 0.99557 0.9966\n                          PC22    PC23   PC24    PC25    PC26    PC27    PC28\nStandard deviation     0.16565 0.15602 0.1344 0.12442 0.09043 0.08307 0.03987\nProportion of Variance 0.00091 0.00081 0.0006 0.00052 0.00027 0.00023 0.00005\nCumulative Proportion  0.99749 0.99830 0.9989 0.99942 0.99969 0.99992 0.99997\n                          PC29    PC30\nStandard deviation     0.02736 0.01153\nProportion of Variance 0.00002 0.00000\nCumulative Proportion  1.00000 1.00000\n```\n\n\n:::\n:::\n\n\n> Q8. Generate a similar plot for principal components 1 and 3. What do you notice about these plots?\n\nThe PC1 vs PC2 plot shows clearer separation between malignant and benign samples than PC1 vs PC3\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(wisc.pr$x) +\n  aes(PC1, PC3, col=diagnosis) +\n  geom_point()\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-9-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# Calculate variance of components.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npr.var <- wisc.pr$sdev^2\nhead(pr.var)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 13.281608  5.691355  2.817949  1.980640  1.648731  1.207357\n```\n\n\n:::\n:::\n\n# Variance explained by each principal component: pve\n\n\n::: {.cell}\n\n```{.r .cell-code}\npve <- pr.var/ sum(pr.var)\n```\n:::\n\n\n# Plot variance explained for each principal component\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(c(1,pve), xlab = \"Principal Component\", \n     ylab = \"Proportion of Variance Explained\", \n     ylim = c(0, 1), type = \"o\")\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-12-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n# Alternative scree plot of same data, data driven y-axis\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbarplot(pve, ylab = \"Explanation For Percent of Variance\",\n     names.arg=paste0(\"PC\",1:length(pve)), las=2, axes = FALSE)\naxis(2, at=pve, labels=round(pve,2)*100 )\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## ggplot based graph\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(factoextra)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWelcome! Want to learn more? See two factoextra-related books at https://goo.gl/ve3WBa\n```\n\n\n:::\n\n```{.r .cell-code}\nfviz_eig(wisc.pr, addlabels = TRUE)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_bar(stat = \"identity\", fill = barfill, color = barcolor, :\nIgnoring empty aesthetic: `width`.\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-14-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Communicating PCA Results\n\n> Q9. For the first principal component, what is the component of the loading vector (i.e. wisc.pr$rotation[,1]) for the feature concave.points_mean? This tells us how much this original feature contributes to the first PC. Are there any features with larger contributions than this one?\n\n\n::: {.cell}\n\n```{.r .cell-code}\npc1 <- wisc.pr$rotation [, \"PC1\"]\nwisc.pr$rotation[\"concave.points_mean\",1]\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2608538\n```\n\n\n:::\n\n```{.r .cell-code}\nmin(pc1)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] -0.2608538\n```\n\n\n:::\n:::\n\n\nThe component of the loading vector for `concave.points_mean` on PC1 is −0.261. This feature has one of the largest absolute loadings on PC1, indicating that it is a major contributor to this principal component.\n\n## Hierarchial clustering \n\n# Scale the wisc.data data using the \"scale()\" function\n\n::: {.cell}\n\n```{.r .cell-code}\nwisc.data <- wisc\ndata.scaled <- scale(wisc.data)\ndata.dist <- dist(data.scaled)\nwisc.hclust <- hclust(data.dist)\nplot(wisc.hclust)\nabline(h=20, col=\"pink\", lty=2)\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-16-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q10. Using plot() and abline() functions, what is the height at which the clustering model has 4 clusters?\n\n~20\n\n## Combining methods\n\nThe idea is to use the new variables like the principal component scores stored in `wisc.pr$x` to provide a more concise and informative representation of the dataset than the original features, which were the 30 variables in `wisc.data`, as the basis for clustering analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npc.dist <- dist(wisc.pr$x[, 1:3])\nwisc.pr.hclust <- hclust(pc.dist, method = \"ward.D2\")\nplot(wisc.pr.hclust)\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-17-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q12. Which method gives your favorite results for the same data.dist dataset? Explain your reasoning.\n\nI prefer the ward d2 method, as it looks distributed the best. It is more even, while the single method looks too convoluted, the average method has weird clumps, and the complete method looks way too spread apart. \n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrps <- cutree(wisc.pr.hclust, k=2)\ntable(grps)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\ngrps\n  1   2 \n203 366 \n```\n\n\n:::\n\n```{.r .cell-code}\ntable(grps, diagnosis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    diagnosis\ngrps   B   M\n   1  24 179\n   2 333  33\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwisc.hclust.clusters <- cutree(wisc.hclust, k=4)\ntable(wisc.hclust.clusters, diagnosis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    diagnosis\nwisc.hclust.clusters   B   M\n                   1  12 165\n                   2   2   5\n                   3 343  40\n                   4   0   2\n```\n\n\n:::\n\n```{.r .cell-code}\nggplot(wisc.pr$x) +\n  aes(PC1, PC2) +\n  geom_point(col=grps)\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-19-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nNow run `table()` with both clustering `grps` and the expert `diagnosis`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(grps, diagnosis)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n    diagnosis\ngrps   B   M\n   1  24 179\n   2 333  33\n```\n\n\n:::\n:::\n\n> Q14. How well do the hierarchical clustering models you created in the previous sections (i.e. without first doing PCA) do in terms of separating the diagnoses? Again, use the table() function to compare the output of each model (wisc.hclust.clusters and wisc.pr.hclust.clusters) with the vector containing the actual diagnoses.\n\nCluster \"1\" has 179 \"M\" Diagnosis\nCluster \"2\" has 333 \"B\" Diagnosis\n\n179 TP\n24 FP\n\n333 TN\n33 FN\n\nSensitivity: TP / (TP+FN)\n\n::: {.cell}\n\n```{.r .cell-code}\n179/(179+33)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.8443396\n```\n\n\n:::\n:::\n\n\nSpecificity: TN / (TN+FP)\n\n::: {.cell}\n\n```{.r .cell-code}\n333/(333+24)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0.9327731\n```\n\n\n:::\n:::\n\n\n## Prediction\n\nWe can use our PCA model for prediction of \n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://tinyurl.com/new-samples-CSV\"\nnew <- read.csv(url)\nnpc <- predict(wisc.pr, newdata=new)\nnpc\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n           PC1       PC2        PC3        PC4       PC5        PC6        PC7\n[1,]  2.576616 -3.135913  1.3990492 -0.7631950  2.781648 -0.8150185 -0.3959098\n[2,] -4.754928 -3.009033 -0.1660946 -0.6052952 -1.140698 -1.2189945  0.8193031\n            PC8       PC9       PC10      PC11      PC12      PC13     PC14\n[1,] -0.2307350 0.1029569 -0.9272861 0.3411457  0.375921 0.1610764 1.187882\n[2,] -0.3307423 0.5281896 -0.4855301 0.7173233 -1.185917 0.5893856 0.303029\n          PC15       PC16        PC17        PC18        PC19       PC20\n[1,] 0.3216974 -0.1743616 -0.07875393 -0.11207028 -0.08802955 -0.2495216\n[2,] 0.1299153  0.1448061 -0.40509706  0.06565549  0.25591230 -0.4289500\n           PC21       PC22       PC23       PC24        PC25         PC26\n[1,]  0.1228233 0.09358453 0.08347651  0.1223396  0.02124121  0.078884581\n[2,] -0.1224776 0.01732146 0.06316631 -0.2338618 -0.20755948 -0.009833238\n             PC27        PC28         PC29         PC30\n[1,]  0.220199544 -0.02946023 -0.015620933  0.005269029\n[2,] -0.001134152  0.09638361  0.002795349 -0.019015820\n```\n\n\n:::\n\n```{.r .cell-code}\nplot(wisc.pr$x[,1:2], col=grps)\npoints(npc[,1], npc[,2], col=\"green\", pch=16, cex=3)\ntext(npc[,1], npc[,2], c(1,2), col=\"blue\")\n```\n\n::: {.cell-output-display}\n![](Class8MH_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n> Q16 Which of these new patients should we prioritize for follow up based on your results?\n\nPatient 1 should be prioritized for a follow up, as their projected PCA scores place them closer to the malignant cluster.\n\n",
    "supporting": [
      "Class8MH_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}