{
  "hash": "4d556ae2746ddb8d6f0290a0c239ddea",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Class 7: Machine Learning 1\"\nauthor: \"Matthew Huang (PID: A17978767)\"\ndate: \"1/27/26\"\nformat:\n  pdf:\n    toc: true\n    toc-depth: 2\n    number-sections: true\n---\n\n# Background\n\nToday we begin our exploration of important machine learning methods, focusing on **clustering** and **dimensional reduction.**\n\nTo start testing these methods, make up some sample data to cluster, where we know what the answer should be.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist( rnorm(3000, mean = 10) )\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-1-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q. Can you generate 30 numbers centered at +3 and 30 \\@ -3 taken at random from a normal dist?\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntmp <- c(rnorm(30, mean = 3),\n         rnorm(30, mean = -3) )\n\nx <- cbind(x = tmp, y = rev(tmp))\nplot(x)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-2-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## K means clustering\n\nThe main function in \"base R\" for K-means clustering is called `kmeans()`, lets try it\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk <- kmeans(x, centers = 2)\n```\n:::\n\n\n> Q. What component of your kmeans result object has the cluster centers?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk$centers\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n          x         y\n1 -2.698849  3.103948\n2  3.103948 -2.698849\n```\n\n\n:::\n:::\n\n\n> Q. What component of your kmeans result has the cluster size? (how many points in cluster)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk$size\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 30 30\n```\n\n\n:::\n:::\n\n\n> Q. What component of your kmeans result has the cluster membership vector? (which points are in cluster)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk$cluster\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 1 1 1 1 1 1 1 1\n[39] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1\n```\n\n\n:::\n:::\n\n\n> Q. Plot the results of clustering (data colored by the clustering result)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x, col = (k$cluster))\npoints(k$centers, col = \"magenta\", pch = 15, cex = 1.5)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-7-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q. Run 'kmeans()' again and cluster into 4 groups, plot results like above with coloring by cluster and cluster centers\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk4 <- kmeans(x, centers = 4)\nplot(x, col = k4$cluster)\npoints(k4$centers, col = \"magenta\", pch = 15, cex = 1.5)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-8-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> **Key point:** Kmenas will always return the clustering that we ask for (this is the \"K\" or \"centers\" in Kmeans).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nk$tot.withinss\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 138.2043\n```\n\n\n:::\n:::\n\n\n# Hierarchical Clustering\n\nThe main function for Hierarchical clustering in base R is called `hclust()`. One of the main differences with respect to the `kmeans()` function is that you can't just pass your input data directly to `hclust()` as it needs a \"distance matrix.We can get this from lots of places including the `dist()` function. `hclust()` more flexible.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nd <- dist(x)\nhc <- hclust(d)\nplot(hc)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-10-1.pdf){fig-pos='H'}\n:::\n:::\n\n\nWe can \"cut the dendrogram or \"tree\" at a given height to yield our \"clusters\", for this we use `cutree()`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(hc)\nabline(h = 7, col=\"red\")\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-11-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\ngrps <- cutree(hc, h = 7)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngrps\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2\n[39] 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2\n```\n\n\n:::\n:::\n\n\n> Q. Plot our data `x` colored by the clusterinv result from `hclust()`?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(x, col = grps)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-13-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n# Principal Component Analysis (PCA)\n\nPCA is a popular dimentionality reduction technique widely used in bioinformatics.\n\n## PCA of UK food data\n\nRead data on food consumption in the UK\n\n\n::: {.cell}\n\n```{.r .cell-code}\nurl <- \"https://tinyurl.com/UK-foods\"\nx <- read.csv(url)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                     X England Wales Scotland N.Ireland\n1               Cheese     105   103      103        66\n2        Carcass_meat      245   227      242       267\n3          Other_meat      685   803      750       586\n4                 Fish     147   160      122        93\n5       Fats_and_oils      193   235      184       209\n6               Sugars     156   175      147       139\n7      Fresh_potatoes      720   874      566      1033\n8           Fresh_Veg      253   265      171       143\n9           Other_Veg      488   570      418       355\n10 Processed_potatoes      198   203      220       187\n11      Processed_Veg      360   365      337       334\n12        Fresh_fruit     1102  1137      957       674\n13            Cereals     1472  1582     1462      1494\n14           Beverages      57    73       53        47\n15        Soft_drinks     1374  1256     1572      1506\n16   Alcoholic_drinks      375   475      458       135\n17      Confectionery       54    64       62        41\n```\n\n\n:::\n:::\n\n\nLooks like row names aren't set properly, let's fix this \n\n\n::: {.cell}\n\n```{.r .cell-code}\nrownames(x) <- x[,1]\nx <- x[,-1]\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                    England Wales Scotland N.Ireland\nCheese                  105   103      103        66\nCarcass_meat            245   227      242       267\nOther_meat              685   803      750       586\nFish                    147   160      122        93\nFats_and_oils           193   235      184       209\nSugars                  156   175      147       139\nFresh_potatoes          720   874      566      1033\nFresh_Veg               253   265      171       143\nOther_Veg               488   570      418       355\nProcessed_potatoes      198   203      220       187\nProcessed_Veg           360   365      337       334\nFresh_fruit            1102  1137      957       674\nCereals                1472  1582     1462      1494\nBeverages                57    73       53        47\nSoft_drinks            1374  1256     1572      1506\nAlcoholic_drinks        375   475      458       135\nConfectionery            54    64       62        41\n```\n\n\n:::\n:::\n\n\nA better way to do this is to fix the row name assignment at import time. \n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- read.csv(url, row.names = 1)\n```\n:::\n\n\n> Q1. How many rows and columns are in your new data frame named x? What R functions could you use to answer this questions?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nx <- dim(x)\nx\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 17  4\n```\n\n\n:::\n:::\n\n\n> Q2. Which approach to solving the ‘row-names problem’ mentioned above do you prefer and why? Is one approach more robust than another under certain circumstances?\n\nI would rather fix the row name assignment at import time, as it appears to be more flexible for usage, and also less complex/convoluted\n\n> Q3. Changing what optional argument in the above barplot() function results in the following plot?\n\nThe stacked barplot is produced by setting the optional argument beside = FALSE in the barplot() function. When beside = FALSE, the bars are stacked rather than displayed side by side.\n\n> Q4. Changing what optional argument in the above ggplot() code results in a stacked barplot figure?\n\nThe stacked barplot is made by changing the position argument in geom_col() from dodge to stack, since stacking is the default behavior, removing the position argument also results in a stacked barplot.\n\n> Q5.  We can use the pairs() function to generate all pairwise plots for our countries. Can you make sense of the following code and resulting figure? What does it mean if a given point lies on the diagonal for a given plot?\n\nThe points show that if the countries had similar values of the food categories,  the points would lie on the diagonal, if the two countries were being compared have different values for certain food categories then the point will not be on the diagonal.\n\n> Q6. Based on the pairs and heatmap figures, which countries cluster together and what does this suggest about their food consumption patterns? Can you easily tell what the main differences between N. Ireland and the other countries of the UK in terms of this data-set?\n\n### Heatmap\n\nWe can install **pheatmap** package with the `install.packages()` command we used before. Make sure to run in consol and not code chunk in quarto.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pheatmap)\n\nurl <- \"https://tinyurl.com/UK-foods\"\nx <- read.csv(url, row.names = 1)\n\npheatmap(as.matrix(x))\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-18-1.pdf){fig-pos='H'}\n:::\n\n```{.r .cell-code}\nlibrary(pheatmap)\npheatmap( as.matrix(x) )\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-18-2.pdf){fig-pos='H'}\n:::\n:::\n\nOf all these plots ontly the `pairs()` plot was really useful, but this took a bit of work to interpret and will ot scale when I am looking at much bigger databases. \n\n## PCA the rescue\n\nThe main function in \"base R\" for PCA is called `prcomp()`\n\n::: {.cell}\n\n```{.r .cell-code}\npca <- prcomp( t(x) )\nsummary(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nImportance of components:\n                            PC1      PC2      PC3     PC4\nStandard deviation     324.1502 212.7478 73.87622 2.7e-14\nProportion of Variance   0.6744   0.2905  0.03503 0.0e+00\nCumulative Proportion    0.6744   0.9650  1.00000 1.0e+00\n```\n\n\n:::\n:::\n\n> Q. How much variance is captured in the first PC?\n\n67.44%\n\n> Q. How many PCs do I need to capture at least 90% of the total variance in the dataset? \n\n2 PCs, that will capture 96.5% of the total variance\n\n> Q. Plot our main PCA results, people can call this different things depending on their field of study, like PC plot, ordienation plot, score plot, PC1 vs PC2 plot, etc... \n\n\n::: {.cell}\n\n```{.r .cell-code}\nattributes(pca)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n$names\n[1] \"sdev\"     \"rotation\" \"center\"   \"scale\"    \"x\"       \n\n$class\n[1] \"prcomp\"\n```\n\n\n:::\n:::\n\nTo generate our PCA score plot, we want the `pca$x` component of the result object\n\n\n::: {.cell}\n\n```{.r .cell-code}\npca$x\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n                 PC1         PC2        PC3           PC4\nEngland   -144.99315   -2.532999 105.768945  1.612425e-14\nWales     -240.52915 -224.646925 -56.475555  4.751043e-13\nScotland   -91.86934  286.081786 -44.415495 -6.044349e-13\nN.Ireland  477.39164  -58.901862  -4.877895  1.145386e-13\n```\n\n\n:::\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmy_cols <- c(\"orange\", \"red\", \"blue\", \"darkgreen\")\nplot(pca$x[,1], pca$x[,2], col=my_cols, pch = 16)\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-22-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n\nggplot(pca$x) + \n  aes(PC1, PC2) +\n  geom_point(cols = my_cols)\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nWarning in geom_point(cols = my_cols): Ignoring unknown parameters: `cols`\n```\n\n\n:::\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-23-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n\n\n\n\n\n\n> Q7. Complete the code below to generate a plot of PC1 vs PC2. The second line adds text labels over the data points.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Create a data frame for plotting\ndf <- as.data.frame(pca$x)\ndf$Country <- rownames(df)\n\n# Plot PC1 vs PC2 with ggplot\nggplot(pca$x) +\n  aes(x = PC1, y = PC2, label = rownames(pca$x)) +\n  geom_point(size = 3) +\n  geom_text(vjust = -0.5) +\n  xlim(-270, 500) +\n  xlab(\"PC1\") +\n  ylab(\"PC2\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-24-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q8. Customize your plot so that the colors of the country names match the colors in our UK and Ireland map and table at start of this document.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- as.data.frame(pca$x)\ndf$Country <- rownames(df)\n\nggplot(pca$x) +\n  aes(x = PC1, y = PC2, label = rownames(pca$x)) +\n  geom_point(size = 3) +\n  geom_text(vjust = -0.5) +\n  xlim(-270, 500) +\n  xlab(\"PC1\") +\n  ylab(\"PC2\") +\n  theme_bw()\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-25-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n## Digging Deeper: Variable Loadings\n\nHow do the original variables (i.e. the 17 differend foods) contribute to our new PCs \n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pca$rotation) +\n  aes(x = PC1, \n      y = reorder(rownames(pca$rotation), PC1)) +\n  geom_col(fill = \"steelblue\") +\n  xlab(\"PC1 Loading Score\") +\n  ylab(\"\") +\n  theme_bw() +\n  theme(axis.text.y = element_text(size = 9))\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-26-1.pdf){fig-pos='H'}\n:::\n:::\n\n\n> Q9. Generate a similar ‘loadings plot’ for PC2. What two food groups feature prominantely and what does PC2 maninly tell us about?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(pca$rotation) +\n  aes(x = PC2, \n      y = reorder(rownames(pca$rotation), PC2)) +\n  geom_col(fill = \"steelblue\") +\n  xlab(\"PC2 Loading Score\") +\n  ylab(\"\") +\n  theme_bw() +\n  theme(axis.text.y = element_text(size = 9))\n```\n\n::: {.cell-output-display}\n![](Class7_files/figure-pdf/unnamed-chunk-27-1.pdf){fig-pos='H'}\n:::\n:::\n",
    "supporting": [
      "Class7_files/figure-pdf"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}